Don't add space in front of comment on empty lines with `insert_eol()`
numToStr/Comment.nvim pull request #131
Opened 2022-03-20 18:28 UTC by melkster

`insert_eol()` used to always add one space in front of the comment. In this PR it checks if the line is empty, and if it is, no space is added in front of the comment.

Before, inserting a comment with `gcA` with cursor on line 2 would result in the following:

```lua
1. local value = 1
2.  -- comment
3. print(value)
```

Now it will look like this:

```lua
1. local value = 1
2. -- comment
3. print(value)
```

An even neater solution would be to use `vim.fn.indent('.')` to calculate the indent level, which would always give the comment a correct indent level in case the line is in an indented environment, for instance inside a function definition or something like that. However I couldn't figure out how to get this to work with tabs if `noexpandtab` is set. `vim.fn.indent('.')` seems to always return the number of spaces (based on `tabstop`).

Do you have an idea of how to get it to work with tabs as well?

2022-03-20 18:35 UTC, numToStr commented
Thanks for working on it. But one thing I want to know is why would anyone prefer `gcc` over `gcA` on a empty line?

2022-03-20 19:40 UTC, melkster commented
@numToStr `gcA` leaves you in insert mode and allows you to type a comment immediatly. So to add the word "comment" as a comment on an empty line you simply type `gcAcomment`. `gcc` leaves you in normal mode so to achieve the same thing you would have to type more characters: `gccA<Space>comment` (The space is there since you have to add the padding manually). Moreover, if you have told Commenter to ignore empty lines with `ignore = '^$'` in `setup()` then nothing happens if you press `gcc` on an empty line.

2022-03-21 13:13 UTC, numToStr requested changes

2022-03-21 13:13 UTC, numToStr commented on lua/Comment/extra.lua
> +    end
```suggestion
    local space= (U.is_empty(line) and '') or (vim.bo.filetype == 'python' and '  ') or ' '
```

2022-03-23 07:41 UTC, numToStr commented
@melkster Just a heads up, I personally don't want to mess up with indents so making `gcA` indent aware is no go for me.

2022-03-23 07:57 UTC, melkster commented
Why is that?

I figured that it's more inutitive if it gives the correct indentation, just like how `cc` puts the cursor on the correct indent. Here's the use case:

```lua
local function foo(val)
  if val ~= nil then

    return 42
  end
end
```

If you put your cursor on the empty line in the function above and type `gcAcomment` with my first fix it would yield this:

```lua
local function foo(val)
  if val ~= nil then
-- comment
    return 42
  end
end
```

with my new fix it does this instead:

```lua
local function foo(val)
  if val ~= nil then
    -- comment
    return 42
  end
end
```

Remember that this behaviour is only for empty lines. The behaviour on other lines is intact meaning that `gcA` does _not_ touch the indent of lines with text on them.

This behaviour doesn't "mess up indents" any more than Neovim's `cc` command does :)

2022-03-23 08:49 UTC, numToStr commented
> Remember that this behaviour is only for empty lines. The behaviour on other lines is intact meaning that gcA does not touch the indent of lines with text on them.

I understand but technically `gcA` only intended to add a comment on a line with some text so adding some extra behavior for something that wasn't intended is not right, IMO.

I'll let the formatter do the indentation anyway so there's that.

2022-03-23 09:26 UTC, Axelwickm commented
Just IMO it's okay for new use-cases to emerge during development as long as it doesn't interfere with the original function, though adding extra complexity is always a bit problematic. I'm not too efficient at using this plugin yet, but on the surface from reading this PR it would seem like having this check would help avoid more pitfalls for the user than it would introduce for the devs.

2022-03-23 09:31 UTC, numToStr commented
> it would seem like having this check would help avoid more pitfalls for the user than it would introduce for the devs.

@Axelwickm are you talking about the leading  space or handling the indentation.

(To be clear i am in favor of removing the trailing space)

2022-03-23 09:32 UTC, Axelwickm commented
@numToStr I was refering to handling indentation.

2022-03-23 10:11 UTC, numToStr requested changes

2022-03-23 10:11 UTC, numToStr commented on lua/Comment/extra.lua
> +        A.nvim_buf_set_lines(0, srow - 1, srow, false, { lcs .. padding })
this won't work if the `commentstring` also contains the right side.

2022-03-23 10:17 UTC, melkster commented on lua/Comment/extra.lua
> +        A.nvim_buf_set_lines(0, srow - 1, srow, false, { lcs .. padding })
You're right! I'll fix that

2022-03-24 13:48 UTC, merged