feat: Add keymap descriptions
numToStr/Comment.nvim pull request #192
Opened 2022-08-03 00:35 UTC by rafamadriz

Let me know if you're happy with the descriptions I added, here's a screenshot of the final result:

![Screenshot_20220802_212934](https://user-images.githubusercontent.com/67771985/182499334-4a4e1a64-0ef9-41c4-b2ef-5957082953db.png)

2022-08-03 05:11 UTC, numToStr commented
Thanks @rafamadriz for putting this together.

Just one thing, isn't it better to start the description with `Toggle comment ...`. Thoughts?

2022-08-03 23:12 UTC, rafamadriz commented
@numToStr I thought about that, but I felt that it was better to have a naming convention where you first start with `name/label` -> `action`. So for example, you have `Comment` and `Uncomment` as names/labels and then action to happen. But besides that, I don't really have a good reason to not do it the other way, just let me know if you want me to change it

2022-08-04 11:09 UTC, numToStr requested changes

2022-08-04 11:09 UTC, numToStr commented on lua/Comment/api.lua
> +                { desc = 'Comment region using single line (visual)' }
```suggestion
                { desc = 'Comment region linewise (visual)' }
```

2022-08-04 11:09 UTC, numToStr commented on lua/Comment/api.lua
> +                { desc = 'Uncomment region using single line (visual)' }
```suggestion
                { desc = 'Uncomment region linewise (visual)' }
```

2022-08-04 11:12 UTC, numToStr commented
@rafamadriz I agree with you. Please review the requested changes then we could go ahead with merging this :)

2022-08-05 06:39 UTC, numToStr approved these changes
Thanks for working on this 👍🏻

2022-08-05 06:39 UTC, merged