remove lockmarks (resolves numToStr/Comment.nvim#219)
numToStr/Comment.nvim pull request #220
Opened 2022-08-25 06:44 UTC by PowerUser64

2022-08-25 06:54 UTC, numToStr requested changes

2022-08-25 06:54 UTC, numToStr commented on lua/Comment/api.lua
> +                ('lua require("Comment.api").%s(%s)'):format(cb, motion and ('%q'):format(motion))
This is clearly not what I wanted, and this will mess up other keybinds. We only need to change the `gc{o,O}` keybinds.

2022-08-25 07:03 UTC, PowerUser64 commented on lua/Comment/api.lua
> +                ('lua require("Comment.api").%s(%s)'):format(cb, motion and ('%q'):format(motion))
Oh, that was my test to see if it would work. Give me a bit, I'm isolating `gco` and `gcO`.

2022-08-25 07:14 UTC, bew commented on lua/Comment/api.lua
> +                ('lua require("Comment.api").%s(%s)'):format(cb, motion and ('%q'):format(motion))
I think @numToStr meant to do this diff:
```diff
diff --git a/lua/Comment/api.lua b/lua/Comment/api.lua
index d9b75c9..6c529e3 100644
--- a/lua/Comment/api.lua
+++ b/lua/Comment/api.lua
@@ -555,9 +555,9 @@ function api.setup(config)

         -- Extra Mappings
         if cfg.mappings.extra then
-            K('n', cfg.extra.below, api.locked('insert.linewise.below'), { desc = 'Comment insert below' })
-            K('n', cfg.extra.above, api.locked('insert.linewise.above'), { desc = 'Comment insert above' })
-            K('n', cfg.extra.eol, api.locked('insert.linewise.eol'), { desc = 'Comment insert end of line' })
+            K('n', cfg.extra.below, api.insert.linewise.below, { desc = 'Comment insert below' })
+            K('n', cfg.extra.above, api.insert.linewise.above, { desc = 'Comment insert above' })
+            K('n', cfg.extra.eol, api.insert.linewise.eol, { desc = 'Comment insert end of line' })
         end

         -- Extended Mappings
```

2022-08-25 07:33 UTC, PowerUser64 commented on lua/Comment/api.lua
> +                ('lua require("Comment.api").%s(%s)'):format(cb, motion and ('%q'):format(motion))
Ohh, okay. That's pretty close to something I had tried. Does the last mapping (`gca`) need to be adjusted too? It doesn't change the number of lines, so I don't think it needs to be changed.

2022-08-25 07:36 UTC, PowerUser64 commented on lua/Comment/api.lua
> +                ('lua require("Comment.api").%s(%s)'):format(cb, motion and ('%q'):format(motion))
I tested it, and last one should be left alone or it will clear the marks on the line (it was probably the original reason for adding `lockmarks`)

2022-08-25 07:44 UTC, bew commented on lua/Comment/api.lua
> +                ('lua require("Comment.api").%s(%s)'):format(cb, motion and ('%q'):format(motion))
> I tested it, and last one should be left alone or it will clear the marks on the line (it was probably the original reason for adding `lockmarks`)

That's surprising, from my understanding `gcA` should only add to the line, but not touch the rest of the line.. No? 
Or do you use nvim api to replace the line, removing all marks?

2022-08-25 07:56 UTC, PowerUser64 commented on lua/Comment/api.lua
> +                ('lua require("Comment.api").%s(%s)'):format(cb, motion and ('%q'):format(motion))
It appears the answer is yes. In [lua/Comment/extra.lua#L96](https://github.com/numToStr/Comment.nvim/blob/master/lua/Comment/extra.lua#L96), it the line is reconstructed with the comment at the end, then used to overwrite the current line.

2022-08-25 08:39 UTC, numToStr commented on lua/Comment/api.lua
> +                ('lua require("Comment.api").%s(%s)'):format(cb, motion and ('%q'):format(motion))
Yes @PowerUser64 is right, `gcA` shouldn't be changed. The reason behind `lockmarks` is that `nvim_buf_set_lines` and even `nvim_buf_set_text` destroys marks #24.

2022-08-27 06:16 UTC, numToStr reviewed
Thanks 👍🏼

2022-08-27 06:16 UTC, numToStr approved these changes

2022-08-27 06:17 UTC, merged