feat(ft): add twig support
numToStr/Comment.nvim pull request #249
Opened 2022-09-29 06:56 UTC by gbprod

https://twig.symfony.com/doc/3.x/templates.html#comments

2022-09-29 07:46 UTC, numToStr commented
Is `html.twig` set by nvim? And what about syntax highlighting?

2022-09-29 12:05 UTC, gbprod commented
When I open `twig` files (without any plugins), neovim set `html.twig` as filetype. I can't find why looking at Nevim source code...
If I set `twig`as filetype in `ft.lua`, it doesn't work at all.

Currently, I use `commentstring` to make your plugin works on twig files.

Syntax highlight doesn't work without plugins in Neovim but I've [made a PR](https://github.com/nvim-treesitter/nvim-treesitter/pull/3529) that still not merged to implements treesitter for twig files.

2022-09-29 12:26 UTC, numToStr commented
> When I open twig files (without any plugins), neovim set html.twig as filetype.

Interesting, can you try it with `nvim --clean`? I am just curious as I can't find any reference of `html.twig` source code and I certainly don't want to add wrong filetype.

> Syntax highlight doesn't work without plugins in Neovim but I've made a PR that still not merged to implements treesitter for twig files.

Nice 👍

2022-09-29 12:40 UTC, numToStr commented
So, I checked it myself, by default `nvim --clean foo.twig` sets filetype to `twig` but there is no highlighting but setting `html.twig` I get highlighting only on html tags.

![image](https://user-images.githubusercontent.com/24727447/193033693-8d4ea4e3-6072-4705-98ad-ce6dc65ac9f1.png)

2022-09-29 19:07 UTC, gbprod commented
Thanks for the feedback, I've also checked and I found that it's vim-polyglot who set `html.twig` as filetype. I'll update my code tomorrow!

2022-09-30 04:40 UTC, numToStr requested changes

2022-09-30 04:40 UTC, numToStr commented on lua/Comment/ft.lua
> +    ['html.twig'] = { '{#%s#}', '{#%s#}' },
Beside filetype, store common commenstring as `M.twig` above and reference it here.

2022-09-30 08:19 UTC, numToStr commented on lua/Comment/ft.lua
> +    twig = { M.twig,  M.twig },
```suggestion
    twig = { M.twig, M.twig },
```

2022-09-30 08:20 UTC, numToStr commented on lua/Comment/ft.lua
> +    twig = '{#%s#}'
```suggestion
    twig = '{#%s#}',
```

2022-09-30 08:20 UTC, numToStr approved these changes

2022-09-30 08:21 UTC, merged