feat: add quarto filetype and enable languages using other languages' parsers
numToStr/Comment.nvim pull request #301
Opened 2023-01-29 20:47 UTC by jmbuhr

This requires the `nvim-treesiter` plugin, as the quarto filetype does not yet have its own treesitter grammar, and this now merged PR in nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter/pull/4212/files

It also makes Comment.nvim work for the other languages in the same list:

https://github.com/nvim-treesitter/nvim-treesitter/blob/cda8b291ef6fc4e04036e2ea6cf0de8aa84c2656/lua/nvim-treesitter/parsers.lua#L4-L23

2023-02-13 09:20 UTC, numToStr requested changes

2023-02-13 09:20 UTC, numToStr commented on lua/Comment/ft.lua
> +    local ok, parser = pcall(vim.treesitter.get_parser, buf, parsername)
We can just create a lookup table with `{ quarto = 'markdown' }` instead of adding `nvim-treesitter` as a dependency for now.

2023-02-13 09:39 UTC, jmbuhr commented on lua/Comment/ft.lua
> +    local ok, parser = pcall(vim.treesitter.get_parser, buf, parsername)
For just quarto, yes, but do you want to maintain the same lookup table that nvim-treesitter has for the other languages as well? Under the assumption that anyone using treesitter is already using nvim-treesitter to install the grammars, it is not really an additional dependency for most people.

2023-02-13 09:47 UTC, numToStr commented on lua/Comment/ft.lua
> +    local ok, parser = pcall(vim.treesitter.get_parser, buf, parsername)
Yes, you are right. But I also don't want to mention that _"nvim-treesitter is required for quarto or whatever filetype"_.

Let us start with quarto and add that table. We can add other filetypes, if someone complains about it.

2023-02-13 10:03 UTC, jmbuhr commented on lua/Comment/ft.lua
> +    local ok, parser = pcall(vim.treesitter.get_parser, buf, parsername)
Would you want the other filetypes already in the table in there as well? They seem pretty sensible to include to me.

2023-02-13 10:15 UTC, numToStr commented on lua/Comment/ft.lua
> +    local ok, parser = pcall(vim.treesitter.get_parser, buf, parsername)
> I hope this back-and-forth is not too much of a bother 🙈

Nah! Improvements are always welcome :)

> Would you want the other filetypes already in the table in there as well?

I would say, let the people complain about it first. In that way, we can save ourselves maintaining extra stuff.

2023-02-13 10:20 UTC, jmbuhr commented on lua/Comment/ft.lua
> +    local ok, parser = pcall(vim.treesitter.get_parser, buf, parsername)
Wise words

2023-02-13 10:25 UTC, merged

2023-02-23 06:37 UTC, numToStr commented
Good news! After the following PRs we might not even need that filetype mapping table, but we might need to wait for next stable neovim release.

- https://github.com/neovim/neovim/pull/22207
- https://github.com/nvim-treesitter/nvim-treesitter/pull/4296

2023-02-23 07:22 UTC, jmbuhr commented
That's great news!