feat(ft): add lean3 support
numToStr/Comment.nvim pull request #375
Opened 2023-06-24 20:56 UTC by MithicSpirit

ft=lean seems to be specifically for lean4. See https://github.com/Julian/lean.nvim/blob/main/ftdetect/lean.lua.

2023-08-01 13:47 UTC, numToStr requested changes

2023-08-01 13:47 UTC, numToStr commented on lua/Comment/ft.lua
> +    lean3 = { M.dash, '/-%s-/' },
I suppose we can move `/-%s-/` to the `M` table as this block comment is similar for `lean` and `lean3`

2023-08-01 18:05 UTC, MithicSpirit commented on lua/Comment/ft.lua
> +    lean3 = { M.dash, '/-%s-/' },
Fair enough, what do you think would be a good name for it? Just `lean`? Or something more descriptive like `slash_dash`?

2023-08-01 19:43 UTC, numToStr commented on lua/Comment/ft.lua
> +    lean3 = { M.dash, '/-%s-/' },
Yeah, `slash_dash` is fine or we could go with `lean_b`. You can pick one, I am fine with either of those.

2023-08-07 11:54 UTC, numToStr approved these changes

2023-08-07 11:55 UTC, merged