docs(plugin): add `lazy.nvim` install instruction
numToStr/Comment.nvim pull request #386
Opened 2023-08-01 12:29 UTC by technicalpickles

An alternative to https://github.com/numToStr/Comment.nvim/pull/367 , without listing out all the keys.

2023-08-01 14:08 UTC, numToStr requested changes

2023-08-01 14:08 UTC, numToStr commented on README.md
> +}
I am looking at this, and it is not clear to me where to put this object. It would be great if you could more instruction to code snippet just like the `vim-plug`.

And I also don't want to recommend any lazy loading method to load the plugin, as I want to keep the instructions simple and clear. If people wants to lazy load, they can always refer to package manager docs.

2023-08-01 14:34 UTC, technicalpickles commented on README.md
> +}
I've added a comment to the snippet.

Added `lazy = false`, but I'm kinda weary of it. I appreciate wanting to keep it simple, but I expect it would be a question lazy.nvim users have about how to best lazily load it, ie if there's an `event` or `keys` to add.

2023-08-01 14:36 UTC, numToStr requested changes

2023-08-02 12:47 UTC, numToStr commented on README.md
> +}
So, you are saying `lazy.nvim` doesn't have any default mode? Like either you have to lazy load with `event`, `keys` etc. or explicitly specify `lazy = false` to not lazy load. 

I don't use lazy.nvim so don't know much about it.

2023-08-07 11:58 UTC, numToStr approved these changes

2023-08-07 11:59 UTC, merged

2023-08-13 04:26 UTC, 9mm commented
This is how I have lazy loaded it BTW. I recommend removing `lazy = false` from the docs as that makes it very confusing (as if the plugin will break otherwise).

Leaving off `lazy = false` will do that anyway.

Here is how I AM lazy loading it:

```lua
return {
  'numToStr/Comment.nvim',
  event = 'InsertEnter',
  config = function()
    require('Comment').setup({})
  end,
}
```

2023-11-26 07:09 UTC, kuator commented on README.md
> +}
> So, you are saying `lazy.nvim` doesn't have any default mode? Like either you have to lazy load with `event`, `keys` etc. or explicitly specify `lazy = false` to not lazy load.
> 
> I don't use lazy.nvim so don't know much about it.

`lazy=false` is a default value for lazy.nvim, setting it is redundant