Add link to video by TJ DeVries
numToStr/Comment.nvim pull request #92
Opened 2021-12-10 20:05 UTC by rodrigc

2021-12-11 07:35 UTC, numToStr requested changes

2021-12-11 07:35 UTC, numToStr commented on README.md
> +### 📺Videos
```suggestion
### 📺 Videos
```

2021-12-11 16:05 UTC, numToStr approved these changes
Thanks 👍

2021-12-11 16:06 UTC, merged

2021-12-11 16:19 UTC, rodrigc commented
Thanks, great plugin!  I wouldn't have known about it without the video from @tjdevries.

2021-12-13 17:25 UTC, tjdevries commented
<3